### PR TITLE
Added Weapon Variants and new SG Shorty

### PR DESCRIPTION
**Pull request by cacapis**
Added Weapon Variants:
* FALCON, SCORPION, REEGAR and VENOM dont have a Concussive variant.
* Variants versions of the starter weapons (M-8 AVENGER,  M-3 PREDATOR, M-23 KATANA, VIPER) are rares, not common.

Added new shotgun SHORTY

### CODE REVIEW

**Comment by NaridaL** [comment]
Did they really add three palette swaps for every weapon? How is one ever supposed to get a level X weapon now XD

**Comment by cacapis** [comment]
Yes, they did it... now you need a lot of free time or a lot of money to unlock the variants.
Variant Weapons (Bulwark, Concussive, Siphon) have "a very small (less than 10%) chance to drop a variant IF you have rank 10 guns (More info in [reddit](https://www.reddit.com/r/MECoOp/comments/6tmfcb/variant_weapon_drops_info_per_bastiaan_frank_mea/))

**Comment by NaridaL** [comment]
Hmm I guess that makes it less terrible...

I'm considering how much effort it would be to have the variants be hidden until you have the base gun at lvl 10...

**Comment by NaridaL** [comment]
Like 10 lines apparently. I pushed it.

**Comment by cacapis** [comment]
Awesome, thank you!

**Pull request merged**
